// non playing leagues would use this

export const randomFormations = [
	{
		name: '4-3-3 Wide',
		formation: '4-3-3',
		centerBack: 2,
		fullBack: 2,
		centralMidfielder: 3,
		centerForward: 3,
	},
	{
		name: '4-3-3 Narrow',
		formation: '4-3-3',
		centerBack: 2,
		fullBack: 2,
		centralMidfielder: 3,
		centerForward: 2,
	},
	{
		name: '4-4-2 Diamond',
		formation: '4-4-2',
		centerBack: 2,
		fullBack: 2,
		centralMidfielder: 4,
		centerForward: 2,
	},
	{
		name: '4-4-2 Flat',
		formation: '4-4-2',
		centerBack: 2,
		fullBack: 2,
		centralMidfielder: 4,
		centerForward: 2,
	},
	{
		name: '4-4-1-1',
		formation: '4-4-1-1',
		centerBack: 2,
		fullBack: 2,
		centralMidfielder: 4,
		centerForward: 1,
		attackingMidfielder: 1,
	},
	{
		name: '4-2-3-1',
		formation: '4-2-3-1',
		centerBack: 2,
		fullBack: 2,
		centralMidfielder: 2,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
	},
	{
		name: '3-5-2',
		formation: '3-5-2',
		centerBack: 3,
		centralMidfielder: 5,
		centerForward: 2,
	},
	{
		name: '3-4-3',
		formation: '3-4-3',
		centerBack: 3,
		centralMidfielder: 4,
		centerForward: 3,
	},
	{
		name: '3-4-2-1',
		formation: '3-4-2-1',
		centerBack: 3,
		centralMidfielder: 4,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
	},
	{
		name: '5-3-2',
		formation: '5-3-2',
		centerBack: 5,
		centralMidfielder: 3,
		centerForward: 2,
	},
	{
		name: '5-2-2-1',
		formation: '5-2-2-1',
		centerBack: 5,
		centralMidfielder: 2,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
	},
	{
		name: '5-2-3',
		formation: '5-2-3',
		centerBack: 5,
		centralMidfielder: 2,
		centerForward: 3,
	},
	{
		name: '4-5-1',
		formation: '4-5-1',
		centerBack: 4,
		centralMidfielder: 5,
		centerForward: 1,
	},
	{
		name: '4-2-2-2',
		formation: '4-2-2-2',
		centerBack: 4,
		centralMidfielder: 2,
		centerForward: 2,
		rightMidfielder: 1,
		leftMidfielder: 1,
	},
	{
		name: '4-1-4-1',
		formation: '4-1-4-1',
		centerBack: 4,
		centralMidfielder: 4,
		centerForward: 1,
		defensiveMidfielder: 1,
	},
	{
		name: '3-6-1',
		formation: '3-6-1',
		centerBack: 3,
		centralMidfielder: 6,
		centerForward: 1,
	},
	{
		name: '3-5-2 Diamond',
		formation: '3-5-2',
		centerBack: 3,
		centralMidfielder: 5,
		centerForward: 2,
	},
	{
		name: '3-5-1-1',
		formation: '3-5-1-1',
		centerBack: 3,
		centralMidfielder: 5,
		centerForward: 1,
		attackingMidfielder: 1,
	},
	{
		name: '3-4-2-1 Diamond',
		formation: '3-4-2-1',
		centerBack: 3,
		centralMidfielder: 4,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
	},
	{
		name: '6-3-1',
		formation: '6-3-1',
		centerBack: 6,
		centralMidfielder: 3,
		centerForward: 1,
	},
	{
		name: '5-4-1',
		formation: '5-4-1',
		centerBack: 5,
		centralMidfielder: 4,
		centerForward: 1,
	},
	{
		name: '5-3-2 Diamond',
		formation: '5-3-2',
		centerBack: 5,
		centralMidfielder: 3,
		centerForward: 2,
	},
	{
		name: '5-2-2-1 Diamond',
		formation: '5-2-2-1',
		centerBack: 5,
		centralMidfielder: 2,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
	},
	{
		name: '2-3-5',
		formation: '2-3-5',
		centerBack: 2,
		centralMidfielder: 3,
		centerForward: 5,
	},
	{
		name: '2-4-4',
		formation: '2-4-4',
		centerBack: 2,
		centralMidfielder: 4,
		centerForward: 4,
	},
	{
		name: '2-4-2-2',
		formation: '2-4-2-2',
		centerBack: 2,
		centralMidfielder: 4,
		centerForward: 2,
		rightMidfielder: 1,
		leftMidfielder: 1,
	},
	{
		name: '2-3-5 Diamond',
		formation: '2-3-5',
		centerBack: 2,
		centralMidfielder: 3,
		centerForward: 5,
	},
	{
		name: '2-3-4-1',
		formation: '2-3-4-1',
		centerBack: 2,
		centralMidfielder: 3,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
	},
	{
		name: '1-4-4-1',
		formation: '1-4-4-1',
		centerBack: 1,
		centralMidfielder: 4,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		defensiveMidfielder: 1,
	},
	{
		name: '1-4-3-2',
		formation: '1-4-3-2',
		centerBack: 1,
		centralMidfielder: 4,
		centerForward: 2,
		rightMidfielder: 1,
		leftMidfielder: 1,
	},
	{
		name: '1-3-4-2',
		formation: '1-3-4-2',
		centerBack: 1,
		centralMidfielder: 3,
		centerForward: 2,
		rightMidfielder: 1,
		leftMidfielder: 1,
	},
	{
		name: '1-3-5-1',
		formation: '1-3-5-1',
		centerBack: 1,
		centralMidfielder: 3,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
	},
	{
		name: '1-2-3-4',
		formation: '1-2-3-4',
		centerBack: 1,
		centralMidfielder: 2,
		centerForward: 4,
		rightMidfielder: 1,
		leftMidfielder: 1,
	},
	{
		name: '1-2-4-3',
		formation: '1-2-4-3',
		centerBack: 1,
		centralMidfielder: 2,
		centerForward: 3,
		rightMidfielder: 1,
		leftMidfielder: 1,
	},
	{
		name: '1-2-4-2-1',
		formation: '1-2-4-2-1',
		centerBack: 1,
		centralMidfielder: 2,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
		defensiveMidfielder: 1,
	},
	{
		name: '1-5-4',
		formation: '1-5-4',
		centerBack: 1,
		centralMidfielder: 5,
		centerForward: 4,
	},
	{
		name: '1-4-5',
		formation: '1-4-5',
		centerBack: 1,
		centralMidfielder: 4,
		centerForward: 5,
	},
	{
		name: '1-4-3-3',
		formation: '1-4-3-3',
		centerBack: 1,
		centralMidfielder: 4,
		centerForward: 3,
		rightMidfielder: 1,
		leftMidfielder: 1,
	},
	{
		name: '1-3-6',
		formation: '1-3-6',
		centerBack: 1,
		centralMidfielder: 3,
		centerForward: 6,
	},
	{
		name: '1-3-5-1 Diamond',
		formation: '1-3-5-1',
		centerBack: 1,
		centralMidfielder: 3,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
	},
	{
		name: '1-2-3-2-2',
		formation: '1-2-3-2-2',
		centerBack: 1,
		centralMidfielder: 2,
		centerForward: 2,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
		defensiveMidfielder: 1,
	},
	{
		name: '1-2-3-4 Diamond',
		formation: '1-2-3-4',
		centerBack: 1,
		centralMidfielder: 2,
		centerForward: 4,
		rightMidfielder: 1,
		leftMidfielder: 1,
	},
	{
		name: '1-2-4-3 Diamond',
		formation: '1-2-4-3',
		centerBack: 1,
		centralMidfielder: 2,
		centerForward: 3,
		rightMidfielder: 1,
		leftMidfielder: 1,
	},
	{
		name: '1-2-4-2-1 Diamond',
		formation: '1-2-4-2-1',
		centerBack: 1,
		centralMidfielder: 2,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
		defensiveMidfielder: 1,
	},
	{
		name: '3-4-3 Diamond',
		formation: '3-4-3',
		centerBack: 3,
		centralMidfielder: 4,
		centerForward: 3,
	},
	{
		name: '3-3-3-1',
		formation: '3-3-3-1',
		centerBack: 3,
		centralMidfielder: 3,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
	},
	{
		name: '2-3-4-1 Diamond',
		formation: '2-3-4-1',
		centerBack: 2,
		centralMidfielder: 3,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
	},
	{
		name: '2-2-4-2',
		formation: '2-2-4-2',
		centerBack: 2,
		centralMidfielder: 2,
		centerForward: 2,
		rightMidfielder: 1,
		leftMidfielder: 1,
	},
	{
		name: '2-2-3-3',
		formation: '2-2-3-3',
		centerBack: 2,
		centralMidfielder: 2,
		centerForward: 3,
		rightMidfielder: 1,
		leftMidfielder: 1,
	},
	{
		name: '2-2-3-2-1',
		formation: '2-2-3-2-1',
		centerBack: 2,
		centralMidfielder: 2,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
		defensiveMidfielder: 1,
	},
	{
		name: '2-2-2-4',
		formation: '2-2-2-4',
		centerBack: 2,
		centralMidfielder: 2,
		centerForward: 4,
		rightMidfielder: 1,
		leftMidfielder: 1,
	},
	{
		name: '2-1-4-3',
		formation: '2-1-4-3',
		centerBack: 2,
		centralMidfielder: 1,
		centerForward: 3,
		rightMidfielder: 1,
		leftMidfielder: 1,
		defensiveMidfielder: 1,
	},
	{
		name: '2-1-3-4',
		formation: '2-1-3-4',
		centerBack: 2,
		centralMidfielder: 1,
		centerForward: 4,
		rightMidfielder: 1,
		leftMidfielder: 1,
		defensiveMidfielder: 1,
	},
	{
		name: '2-1-3-2-2',
		formation: '2-1-3-2-2',
		centerBack: 2,
		centralMidfielder: 1,
		centerForward: 2,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
		defensiveMidfielder: 1,
	},
	{
		name: '1-2-2-4-1',
		formation: '1-2-2-4-1',
		centerBack: 1,
		centralMidfielder: 2,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
		defensiveMidfielder: 1,
	},
	{
		name: '1-2-2-3-2',
		formation: '1-2-2-3-2',
		centerBack: 1,
		centralMidfielder: 2,
		centerForward: 2,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
		defensiveMidfielder: 1,
	},
	{
		name: '1-2-1-4-2',
		formation: '1-2-1-4-2',
		centerBack: 1,
		centralMidfielder: 2,
		centerForward: 2,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
		defensiveMidfielder: 1,
	},
	{
		name: '1-1-3-3-2',
		formation: '1-1-3-3-2',
		centerBack: 1,
		centralMidfielder: 1,
		centerForward: 2,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
		defensiveMidfielder: 1,
	},
	{
		name: '1-1-4-2-2',
		formation: '1-1-4-2-2',
		centerBack: 1,
		centralMidfielder: 1,
		centerForward: 2,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
		defensiveMidfielder: 1,
	},
	{
		name: '1-1-3-4-1',
		formation: '1-1-3-4-1',
		centerBack: 1,
		centralMidfielder: 1,
		centerForward: 1,
		rightMidfielder: 1,
		leftMidfielder: 1,
		attackingMidfielder: 1,
		defensiveMidfielder: 1,
	},
];
